import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['Manager','Employe'],
    submenu: [],
  },
  //employee and pm 
{
  path: '/employee/dashboard',
  title:  'MENUITEMS.DASHBOARD.TEXT',
  iconType: 'material-icons-two-tone',
  icon: 'space_dashboard',
  class: '',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: ['Employe','Rh'],
  submenu: [],
},
  
  {
    path: '/admin/dashboard/dashboard2',
    title:  'MENUITEMS.DASHBOARD.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Manager'],
    submenu: [],
  },
 
  {
    path: '/admin/rh/rhlist',
    title: 'MENUITEMS.ProjectManagers.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'supervised_user_circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Manager'],
    submenu: [],
  },
  {
    path: '/admin/employee/employeelist',
    title: 'Employee',
    iconType: 'material-icons-two-tone',
    icon: 'people_alt',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Manager'],
    submenu: [],
  },
  {
    path: '/admin/all/alllist',
    title: 'All',
    iconType: 'material-icons-two-tone',
    icon: 'people_alt',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Manager'],
    submenu: [],
  },
  


  // {
  //   path: '',
  //   title: 'MENUITEMS.Acceuil.TEXT',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'event',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Manager'],
  //   submenu: [
  //     {
  //       path: '/admin/insight/edit-insight',
  //       title: 'MENUITEMS.Acceuil.LIST.My-Post',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //     {
  //       path: '/admin/insight/insight-profile',
  //       title: 'MENUITEMS.Acceuil.LIST.Acceuil',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },

 {
    path: '/admin/ticket/ticketlist',
    title: 'Ticket',
    iconType: 'material-icons-two-tone',
    icon: 'event',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Rh'],
    submenu: [],
  },

//employee

{
  path:'/admin/absence/my-absence',
  title: 'Absence',
  iconType: 'material-icons-two-tone',
  icon: 'description',
  class: '',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: ['Employe','Rh'],
  submenu: [],
},

//pm
{
  path:'/admin/absence/all-absence',
  title: 'Absence',
  iconType: 'material-icons-two-tone',
  icon: 'description',
  class: '',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: ['Manager'],
  submenu: [],
},

// {
//   path: '',
//   title: 'MENUITEMS.Acceuil.TEXT',
//   iconType: 'material-icons-two-tone',
//   icon: 'event',
//   class: 'menu-toggle',
//   groupTitle: false,
//   badge: '',
//   badgeClass: '',
//   role: ['Employe' ,'Rh'],
//   submenu: [
//     {
//       path: '/admin/insight/edit-insight',
//       title: 'MENUITEMS.Acceuil.LIST.My-Post',
//       iconType: '',
//       icon: '',
//       class: 'ml-menu',
//       groupTitle: false,
//       badge: '',
//       badgeClass: '',
//       role: [''],
//       submenu: [],
//     },
//     {
//       path: '/admin/insight/insight-profile',
//       title: 'MENUITEMS.Acceuil.LIST.Acceuil',
//       iconType: '',
//       icon: '',
//       class: 'ml-menu',
//       groupTitle: false,
//       badge: '',
//       badgeClass: '',
//       role: [''],
//       submenu: [],
//     },
//   ],
// },


  // Common Modules

  {
    path: '',
    title: 'Apps',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['Manager','Employe','Rh'],
    submenu: [],
  },
  {
    path: 'calendar',
    title: 'Calendar',
    iconType: 'material-icons-two-tone',
    icon: 'event_note',
    class: '',
    groupTitle: false,
    badge: 'New',
    badgeClass: 'badge bg-blue sidebar-badge float-end',
    role: ['Manager'],
    submenu: [],
  },
  {
    path: '/apps/chat',
    title: 'Chat',
    iconType: 'material-icons-two-tone',
    icon: 'chat',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Manager', 'Employe','Rh'],
    submenu: [],
  },

];
