eureka:
  client:
    register-with-eureka: false
server:
  port: 8098
spring:
  application:
    name: gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: allergies
#          uri: http://localhost:8090
#          predicates:
#            - path=/api/v1/allergies/**
#        - id: allergies
#          uri: http://localhost:8090
#          predicates:
#            - path=/api/v1/allergies/**


  config:
    import: optional:configserver:http://localhost:8888