spring:
  application:
    name: AuthLinsoft
  datasource:
    url: jdbc:mysql://localhost:3306/AuthLinsoft?createDatabaseIfNotExist=true&useSSL=false
    username: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
#  mail:
#        host: smtp.example.com
#        port: 587
#        username: nawres.askri@esprit.com
#        password: 12360636nawrous
#        properties:
#        mail.smtp.auth: true
#        mail.smtp.starttls.enable: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: rhlinsoft@gmail.com
    password: zwcm ehzh uqoo egji
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  config:
    import: optional:configserver:http://localhost:8888

#springconfig
server:
  port: 8076

  #eureka
  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
# App Properties
bezkoder:
  app:
    jwtSecret: "======================BezKoder=Spring==========================="
    jwtExpirationMs: 86400000

application:
  mailing:
    frontend:
      activation-url: "http://localhost:4200/authentication"




